// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "openllmsh/daemon",
  tag: "v2.6.27",
  targets: [
    "darwin-arm64",
    "darwin-x64-baseline",
    "linux-x64-baseline",
    "linux-arm64",
  ],
  sha256: {
    "darwin-arm64":
      "ff10111db0d6f70988356656ab8d5ebfec1c48466020afe4c8bfdd828c4cf43a",
    "darwin-x64-baseline":
      "83ce9371e451ad230d7c1c22917aa306c82f3b78f46745752c13ee716eb0a066",
    "linux-x64-baseline":
      "6ea8dabb3ed94697f77778967567136d4f7f3792e3d5cace6e43b62c94895aef",
    "linux-arm64":
      "54500a2caef0bb89fa3617f5aae0f1fb5fc48ef4e9ad053af361ed6c635a7a58",
  },
};
