// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "quantidexyz/openllmd",
  tag: "v1.4.8-security.3",
  targets: ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"],
  sha256: {
    "darwin-arm64":
      "c9a8b66724d5ad1a71cb513d55edac51a00f59ba25e9a301ff19059a9b06df4e",
    "darwin-x64":
      "64ea4774f7104511bd68f76b57a10fc92c9cbe27a9feb4cd78aeb512aac76bfe",
    "linux-x64":
      "defd0661238b0694c43e85e61217c8f2499718773f586a24c132e394e89ed244",
    "linux-arm64":
      "1c69ba636eca7eec8c99f1543c02d330793549f05cd086bb6da2fbd537538c8d",
  },
};
