// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "quantidexyz/openllmd",
  tag: "v1.3.10",
  targets: ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"],
  sha256: {
    "darwin-arm64":
      "1705dacc62a843307c648771f95f96734a8d2ff0919df719d815f1b3148e5405",
    "darwin-x64":
      "7dbcf71000d42e4b5e19d11ab63d59c08c8a13de7da328cb663f891397ad03b8",
    "linux-x64":
      "dde109ae326e7cb0982f14d64681e920b0db41aa314e16cfcf9724a5b44309e8",
    "linux-arm64":
      "66d85148117d808f91e374c5c1fbf5d3f26e5f14acf2f5ad84ad116bf9cc1981",
  },
};
