// AUTOGENERATED by packages/release (bun run release:daemon) — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun run release:daemon`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "quantidexyz/openllmd",
  tag: "v1.3.7",
  targets: ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"],
  sha256: {
    "darwin-arm64":
      "233ba83d1cee45c629fb75e1dbe12c45f42a7bd92fe73f998e6796caef12b1e2",
    "darwin-x64":
      "11c9658d0d90c15507b05d397bf2c1fc97ece001e7ca3838e26622e10b5ec087",
    "linux-x64":
      "1f725765a5a30ae172a263cb8e59b7b6ea80a256c1c2b4d3c9fc746078b271d9",
    "linux-arm64":
      "1930b94e03fb36c6cbf51630cfe97bb4680e3a8aa05f2776d2b3cab9d17283d2",
  },
};
