// AUTOGENERATED by packages/daemon/scripts/release.ts — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun packages/daemon/scripts/release.ts`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "quantidexyz/openllmd",
  tag: "v1.3.0-alpha.0",
  targets: ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"],
  sha256: {
    "darwin-arm64": "1f0481426e057f360924edb9792a814c1fa4e796ab54fd93a30de70106c804b5",
    "darwin-x64": "4e99764988511d76831f657e72e67a570e5d8745427592c5b2fc7dd3b69979e6",
    "linux-x64": "8b770ae6f9c87af737798461187c21c9e869fb26bd06be12547fa99dc13ae3b3",
    "linux-arm64": "bbf7c63d1ceb91d77f3c7e6e5c2b9871f77e2c5b289f85f61667f414dafe9adb",
  },
};
