// AUTOGENERATED by packages/daemon/scripts/release.ts — DO NOT EDIT BY HAND.
// COMMITTED on purpose (unlike the gitignored bundle outputs): this pins the
// published daemon release that the cloud's /api/daemon/binary route redirects
// to. Re-run `bun packages/daemon/scripts/release.ts`, then commit this file.
//
// `tag: ""` means nothing is published yet — the route returns 503 until the
// first release script run fills in the tag + checksums.

import type { TDaemonRelease } from "./release-types";

export const DAEMON_RELEASE: TDaemonRelease = {
  repo: "quantidexyz/openllmd",
  tag: "v1.3.2",
  targets: ["darwin-arm64", "darwin-x64", "linux-x64", "linux-arm64"],
  sha256: {
    "darwin-arm64":
      "2b3fbcbb415fa27272721df184964b591f725ae61e7aa7057b5a831b212c32d9",
    "darwin-x64":
      "e63c88be57238ae8f3dcb9650c77e4b2d96a57226a9fee5f32438dd9b973d5e6",
    "linux-x64":
      "c3e3492b02016123b134dd550553f73220cddd7f8d9ad9be23ad9b373ceabd9b",
    "linux-arm64":
      "cc5ce204dd0cdadb1908fbf8d2af07e172b5bec1b7edfdc96e97334c03eb9745",
  },
};
