#!/usr/bin/env bash
# ============================================================================
# OpenLLM daemon — self-contained installer for __TARGET__
# Auto-generated by `bun run daemon:dist` from local source (version __VERSION__).
# DO NOT EDIT — regenerate with: bun run daemon:dist
#
# This IS the upstream installer (packages/setup/daemon/install.sh) run VERBATIM,
# with the locally-built, gzipped daemon binary embedded at the end (base64).
# The ONLY change from a production install is transport: a tiny `curl` shim
# feeds the embedded binary + its sha256 to the unchanged download+verify step,
# so the binary needs no gateway/network. Every other step — checksum verify,
# install to ~/.openllm/bin, PATH symlink, daemon.env, macOS codesign,
# `openllmd start`, shell completion — runs EXACTLY as in production.
#
# Usage on a __TARGET__ machine (env names match the real install + daemon.env):
#   OPENLLM_CLOUD_ORIGIN=https://your-cloud OPENLLM_API_KEY=sk-llm-... bash "$0"
# Both are optional when ~/.openllm/daemon.env already exists — its values are
# reused. OPENLLM_CLOUD_ORIGIN otherwise defaults to __CLOUD_DEFAULT__.
#
# NOTE: with a reachable cloud the daemon's self-update may later replace this
# binary with the published release. To exercise THIS binary in isolation, point
# GATEWAY_ORIGIN at a staging or unreachable origin.
# ============================================================================
set -euo pipefail

OPENLLMD_DIST_TARGET="__TARGET__"
OPENLLMD_DIST_SHA="__SHA__"

# --- guard: refuse the wrong-arch installer (the embedded binary wouldn't run) ---
_d_os=$(uname -s); _d_arch=$(uname -m)
case "$_d_os" in Darwin) _d_os=darwin ;; Linux) _d_os=linux ;; *) echo "Unsupported OS: $_d_os" >&2; exit 1 ;; esac
case "$_d_arch" in arm64|aarch64) _d_arch=arm64 ;; x86_64|amd64) _d_arch=x64 ;; *) echo "Unsupported arch: $_d_arch" >&2; exit 1 ;; esac
if [ "${_d_os}-${_d_arch}" != "$OPENLLMD_DIST_TARGET" ]; then
  echo "This installer is built for ${OPENLLMD_DIST_TARGET}, but this machine is ${_d_os}-${_d_arch}." >&2
  echo "Copy openllmd-${_d_os}-${_d_arch}.install.sh to this machine instead." >&2
  exit 1
fi

# --- portable base64 decode (GNU '-d' vs BSD/macOS '-D') --------------------
if printf '' | base64 -d >/dev/null 2>&1; then _b64d=(base64 -d); else _b64d=(base64 -D); fi

# --- stage the embedded binary as a local 'gateway' payload -----------------
# Lay the binary + sha256 out at the SAME path shape the gateway serves
# (`/api/daemon/binary/<target>(.sha256)`) so the curl shim below can map a
# binary_url straight onto these files — install.sh stays byte-for-byte upstream.
OPENLLMD_DIST_WORK="$(mktemp -d)"
mkdir -p "$OPENLLMD_DIST_WORK/payload/api/daemon/binary" "$OPENLLMD_DIST_WORK/shim"
awk 'f{print} /^__OPENLLMD_GZ_BEGIN__$/{f=1}' "$0" | "${_b64d[@]}" \
  > "$OPENLLMD_DIST_WORK/payload/api/daemon/binary/$OPENLLMD_DIST_TARGET"
printf '%s  openllmd-%s\n' "$OPENLLMD_DIST_SHA" "$OPENLLMD_DIST_TARGET" \
  > "$OPENLLMD_DIST_WORK/payload/api/daemon/binary/$OPENLLMD_DIST_TARGET.sha256"

# --- curl shim: serve the embedded binary; pass anything else to real curl --
# install.sh only curls the binary + its .sha256 from $GATEWAY_ORIGIN; intercept
# exactly those (any URL containing /api/daemon/binary/) and copy from the local
# payload. Everything else (none, during install) falls through to the real curl
# resolved from the pre-shim PATH.
cat > "$OPENLLMD_DIST_WORK/shim/curl" <<'OPENLLMD_SHIM'
#!/usr/bin/env bash
real_curl="$(PATH="$OPENLLMD_DIST_REALPATH" command -v curl || true)"
url=""; out=""
args=("$@")
for ((i=0; i<${#args[@]}; i++)); do
  case "${args[$i]}" in
    -o) out="${args[$((i+1))]}" ;;
    http://*|https://*|file://*) url="${args[$i]}" ;;
  esac
done
if [[ "$url" == *"/api/daemon/binary/"* ]]; then
  rel="${url##*/api/daemon/binary/}"
  src="$OPENLLMD_DIST_PAYLOAD/api/daemon/binary/$rel"
  if [[ ! -f "$src" ]]; then echo "curl-shim: no embedded payload for $url" >&2; exit 22; fi
  if [[ -n "$out" ]]; then cp "$src" "$out"; else cat "$src"; fi
  exit 0
fi
if [[ -z "$real_curl" ]]; then echo "curl-shim: real curl not found (args: $*)" >&2; exit 127; fi
exec "$real_curl" "$@"
OPENLLMD_SHIM
chmod +x "$OPENLLMD_DIST_WORK/shim/curl"

export OPENLLMD_DIST_REALPATH="$PATH"
export OPENLLMD_DIST_PAYLOAD="$OPENLLMD_DIST_WORK/payload"
export PATH="$OPENLLMD_DIST_WORK/shim:$PATH"

# --- credentials: same OPENLLM_* names as the real install + daemon.env ------
# The production setup flow pipes the key as OPENLLM_API_KEY (the daemon's
# config_var) and the daemon boots from OPENLLM_CLOUD_ORIGIN; accept the SAME
# names here. Precedence:
#   1. an explicit OPENLLM_* value in the environment;
#   2. the value already in ~/.openllm/daemon.env (re-run / re-pair in place);
#   3. the baked default origin (the key stays empty if nothing supplies it).
# install.sh always reads/writes $HOME/.openllm/daemon.env, so reuse from there;
# install.sh itself separately preserves the minted OPENLLM_DEVICE_ID.
OPENLLMD_DIST_ENV_FILE="$HOME/.openllm/daemon.env"
_openllmd_dist_reuse() {  # $1=key → its value in the existing daemon.env (or "")
  [ -f "$OPENLLMD_DIST_ENV_FILE" ] || return 0
  grep -E "^$1=" "$OPENLLMD_DIST_ENV_FILE" 2>/dev/null | head -n1 | cut -d= -f2- || true
}
if [ -f "$OPENLLMD_DIST_ENV_FILE" ]; then
  echo "Found existing $OPENLLMD_DIST_ENV_FILE — reusing its OPENLLM_CLOUD_ORIGIN + OPENLLM_API_KEY where not overridden." >&2
fi
OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-$(_openllmd_dist_reuse OPENLLM_CLOUD_ORIGIN)}"
OPENLLM_API_KEY="${OPENLLM_API_KEY:-$(_openllmd_dist_reuse OPENLLM_API_KEY)}"
OPENLLM_CLOUD_ORIGIN="${OPENLLM_CLOUD_ORIGIN:-__CLOUD_DEFAULT__}"

# Map the OPENLLM_* inputs onto the names the embedded install.sh consumes.
export GATEWAY_ORIGIN="$OPENLLM_CLOUD_ORIGIN"
export API_KEY="$OPENLLM_API_KEY"
export USAGE_URL="${USAGE_URL:-}"
if [ -z "$API_KEY" ]; then
  echo "Note: no OPENLLM_API_KEY set and none in daemon.env — the daemon will install and run locally but won't pair with a cloud." >&2
fi

_openllmd_dist_cleanup() { rm -rf "$OPENLLMD_DIST_WORK"; }
trap _openllmd_dist_cleanup EXIT

# ======================= begin verbatim install.sh ==========================
__INSTALL_SH_BODY__
# ======================== end verbatim install.sh ===========================

# install.sh installs its OWN EXIT trap (for ITS temp files), replacing ours —
# so clean our staging dir explicitly now that it has completed successfully.
_openllmd_dist_cleanup
trap - EXIT
exit 0

__OPENLLMD_GZ_BEGIN__
__PAYLOAD_BASE64__
